spring:
  application:
    name: consumer
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 9466c0d9-b5bd-4f1a-9936-10e37656afdf
        cluster-name: SZ
        metadata:
          version: v1
          target-version: v1
    sentinel:
      transport:
        dashboard: localhost:8080
dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: provider

server:
  port: 3000
ribbon:
  eager-load:
    enabled: true
    clients: provider
#java代码形式配置细粒度日志
#logging:
#  level:
#    com.hzihui.cloud.alibaba.service.ProductService: debug
#服务监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
